# Generated by Django 4.2 on 2025-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='historico_status',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
