# Generated by Django 4.2 on 2025-09-17 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_cartaokanban_colunakanban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='grupos/arquivos/')),
                ('tipo_arquivo', models.CharField(max_length=100)),
                ('tamanho', models.PositiveIntegerField()),
                ('pasta', models.CharField(blank=True, max_length=200)),
                ('tipo_organizacao', models.CharField(choices=[('tarefa', 'Por Tarefa'), ('mes', 'Por Mês'), ('categoria', 'Por Categoria'), ('livre', 'Livre')], default='livre', max_length=20)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('upload_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Arquivo do Grupo',
                'verbose_name_plural': 'Arquivos dos Grupos',
                'ordering': ['-upload_em'],
            },
        ),
        migrations.CreateModel(
            name='ConviteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('administrador', 'Administrador'), ('moderador', 'Moderador'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Convite de Grupo',
                'verbose_name_plural': 'Convites de Grupos',
            },
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('administrador', 'Administrador'), ('moderador', 'Moderador'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20)),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Membro do Grupo',
                'verbose_name_plural': 'Membros dos Grupos',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarefa_atribuida', 'Tarefa Atribuída'), ('prazo_proximo', 'Prazo Próximo'), ('prazo_vencido', 'Prazo Vencido'), ('mencao', 'Menção'), ('comentario', 'Novo Comentário'), ('status_alterado', 'Status Alterado'), ('convite_grupo', 'Convite para Grupo'), ('membro_adicionado', 'Membro Adicionado')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação do Grupo',
                'verbose_name_plural': 'Notificações dos Grupos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='tarefa',
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='upload_por',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='mencoes',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='tarefa',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='membros',
        ),
        migrations.AddField(
            model_name='grupo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='grupos/avatares/'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='cor_personalizada',
            field=models.CharField(default='#3498db', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Cor deve estar no formato hexadecimal #RRGGBB')]),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['ativo'], name='core_grupo_ativo_f316e4_idx'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['criado_em'], name='core_grupo_criado__b134b9_idx'),
        ),
        migrations.DeleteModel(
            name='Anexo',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Membro',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.AddField(
            model_name='notificacaogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.grupo'),
        ),
        migrations.AddField(
            model_name='notificacaogrupo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_grupo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membrogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupo'),
        ),
        migrations.AddField(
            model_name='membrogrupo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convitegrupo',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convitegrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.grupo'),
        ),
        migrations.AddField(
            model_name='convitegrupo',
            name='usado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_usados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arquivogrupo',
            name='arquivo_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='core.arquivogrupo'),
        ),
        migrations.AddField(
            model_name='arquivogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.grupo'),
        ),
        migrations.AddField(
            model_name='arquivogrupo',
            name='upload_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificacaogrupo',
            index=models.Index(fields=['usuario', 'lida'], name='core_notifi_usuario_0689d0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaogrupo',
            index=models.Index(fields=['grupo', 'criado_em'], name='core_notifi_grupo_i_2c9478_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaogrupo',
            index=models.Index(fields=['tipo', 'criado_em'], name='core_notifi_tipo_c41400_idx'),
        ),
        migrations.AddIndex(
            model_name='membrogrupo',
            index=models.Index(fields=['grupo', 'ativo'], name='core_membro_grupo_i_4139af_idx'),
        ),
        migrations.AddIndex(
            model_name='membrogrupo',
            index=models.Index(fields=['usuario', 'ativo'], name='core_membro_usuario_12dd4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membrogrupo',
            unique_together={('usuario', 'grupo')},
        ),
        migrations.AddIndex(
            model_name='convitegrupo',
            index=models.Index(fields=['token'], name='core_convit_token_abec23_idx'),
        ),
        migrations.AddIndex(
            model_name='convitegrupo',
            index=models.Index(fields=['expira_em', 'usado'], name='core_convit_expira__1b4cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivogrupo',
            index=models.Index(fields=['grupo', 'pasta'], name='core_arquiv_grupo_i_47e491_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivogrupo',
            index=models.Index(fields=['upload_em'], name='core_arquiv_upload__a307fb_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivogrupo',
            index=models.Index(fields=['tipo_organizacao'], name='core_arquiv_tipo_or_2ee480_idx'),
        ),
    ]
