# Generated by Django 4.2 on 2025-09-17 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_arquivogrupo_convitegrupo_membrogrupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(related_name='grupos_participando', through='core.MembroGrupo', to=settings.AUTH_USER_MODEL),
        ),
    ]
