# Generated by Django 4.2 on 2025-08-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tarefa_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grupo'),
        ),
    ]
