# Generated by Django 4.2 on 2025-09-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_grupo_membros'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a_fazer', 'A Fazer'), ('em_andamento', 'Em andamento'), ('aguardando_feedback', 'Aguardando feedback'), ('concluido', 'Concluído')], default='a_fazer', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('coluna_kanban', models.CharField(default='a_fazer', max_length=20)),
                ('ordem_kanban', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('historico_status', models.JSONField(blank=True, default=list)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='tarefas_colaborando', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_grupo_criadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.grupo')),
                ('responsavel_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa do Grupo',
                'verbose_name_plural': 'Tarefas dos Grupos',
                'ordering': ['ordem_kanban', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mencoes', models.ManyToManyField(blank=True, related_name='mencionado_em_tarefas', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.tarefagrupo')),
            ],
            options={
                'verbose_name': 'Comentário da Tarefa',
                'verbose_name_plural': 'Comentários das Tarefas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('concluido', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.tarefagrupo')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tarefas/anexos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(max_length=100)),
                ('tamanho', models.PositiveIntegerField()),
                ('upload_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comentariotarefa')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.tarefagrupo')),
                ('upload_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo da Tarefa',
                'verbose_name_plural': 'Anexos das Tarefas',
                'ordering': ['-upload_em'],
            },
        ),
        # Adiciona índices
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_tarefa_grupo_status_idx ON core_tarefagrupo(grupo_id, status);",
            reverse_sql="DROP INDEX IF EXISTS core_tarefa_grupo_status_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_tarefa_status_prazo_idx ON core_tarefagrupo(status, prazo);",
            reverse_sql="DROP INDEX IF EXISTS core_tarefa_status_prazo_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_tarefa_kanban_idx ON core_tarefagrupo(grupo_id, coluna_kanban, ordem_kanban);",
            reverse_sql="DROP INDEX IF EXISTS core_tarefa_kanban_idx;"
        ),
    ]
