# Generated by Django 4.2 on 2025-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tarefa_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaofinanceira',
            name='anexo',
            field=models.FileField(blank=True, help_text='Anexo opcional para a transação', null=True, upload_to='transacoes/'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='parcelas',
            field=models.IntegerField(default=1, help_text='Número de parcelas (1 para pagamento único)'),
        ),
    ]
