# Generated by Django 4.2 on 2025-09-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_tarefagrupo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaogrupo',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.tarefagrupo'),
        ),
    ]
