# Generated by Django 4.2 on 2025-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transacaofinanceira_anexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='notificar_despesas_recorrentes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='notificar_receitas_programadas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='notificar_transacoes_vencidas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data em que a transação foi paga', null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='pago',
            field=models.BooleanField(default=False, help_text='Indica se a transação foi paga'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='recorrente',
            field=models.BooleanField(default=False, help_text='Indica se a transação é recorrente'),
        ),
    ]
