# Generated by Django 4.2 on 2025-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_tarefa_to_notificacao'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tarefagrupo',
            index=models.Index(fields=['grupo', 'status'], name='core_tarefa_grupo_i_587e19_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefagrupo',
            index=models.Index(fields=['status', 'prazo'], name='core_tarefa_status_324d53_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefagrupo',
            index=models.Index(fields=['grupo', 'coluna_kanban', 'ordem_kanban'], name='core_tarefa_grupo_i_0030b6_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefagrupo',
            index=models.Index(fields=['responsavel_principal'], name='core_tarefa_respons_80b926_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefagrupo',
            index=models.Index(fields=['criado_em'], name='core_tarefa_criado__d7aecc_idx'),
        ),
    ]
