# Generated by Django 4.2 on 2025-08-20 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_configuracaonotificacao_notificar_despesas_recorrentes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cartão Kanban',
                'verbose_name_plural': 'Cartões Kanban',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ColunaKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cor', models.CharField(default='#3498db', max_length=20)),
                ('limite_cartoes', models.PositiveIntegerField(blank=True, help_text='Limite máximo de cartões nesta coluna (opcional)', null=True)),
            ],
            options={
                'verbose_name': 'Coluna Kanban',
                'verbose_name_plural': 'Colunas Kanban',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='QuadroKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros_criados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='core.grupo')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quadro Kanban',
                'verbose_name_plural': 'Quadros Kanban',
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.cartaokanban')),
                ('coluna_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='core.colunakanban')),
                ('coluna_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='core.colunakanban')),
                ('movido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Históricos de Movimentações',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddField(
            model_name='colunakanban',
            name='quadro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='core.quadrokanban'),
        ),
        migrations.AddField(
            model_name='cartaokanban',
            name='coluna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.colunakanban'),
        ),
        migrations.AddField(
            model_name='cartaokanban',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartaokanban',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='cartoes_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartaokanban',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='core.tarefa'),
        ),
    ]
